name: calculator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  provider: ^6.0.0
  connectivity_plus: ^3.0.3
  battery_plus: ^2.0.3
  fluttertoast: ^8.1.1
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  http: ^0.13.4
  image_picker: ^0.8.4+8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/default_profile_picture.png
    - assets/lang/en.json
    - assets/lang/fr.json

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated